config/routes.rb
Rails.application.routes.draw do
  concern :transaction_historyable do
    resources :transaction_histories, param: :number, only: [:index] do
      collection do
        get 'debit', controller: 'transaction_histories', action: 'debit'
        get 'credit', controller: 'transaction_histories', action: 'credit'
        post 'new_debit', controller: 'transaction_histories', action: 'new_debit'
        post 'new_credit', controller: 'transaction_histories', action: 'new_credit'
      end
    end
  end

  resources :users, :teams, :stocks, param: :code do
    concerns :transaction_historyable
  end
  
  get '*path' => redirect('/')
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/clients/stock.rb
class Stock < Client
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]

  # GET /stocks or /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1 or /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks or /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to stock_url(@stock.code), notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to stock_url(@stock.code), notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find_by_code(params[:code])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.fetch(:stock, {}).permit(:name, :email, :code)
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.erb
<%= form_with(model: stock, include_id: false) do |form| %>
  <% if stock.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
        <% stock.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <form>
    <div class="col  mb-2">
      <div class="card" style="width: 36rem;">
        <div class="card-body">
            <%= form.label :name %>
            <%= form.text_field :name %>
            <%= form.label :email %>
            <%= form.text_field :email %>
            <%= form.hidden_field :code %>
          <button type="submit" class="btn btn-primary mb-2">Simpan</button>
        </div>
      </div>
    </div>

  </form>
<% end %>

app/views/stocks/_stock.html.erb
<div id="<%= dom_id stock %>">
  <p>
    <strong>Name:</strong>
    <%= stock.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= stock.email %>
  </p>

</div>

app/views/stocks/edit.html.erb
<div class="col">
  <h1>Editing stock</h1>

  <%= render "form", stock: @stock %>

  <br>

  <div>
    <%= link_to "Show this stock", stock_path(@stock.code), class: "btn btn-info" %>
    <%= link_to "Back to stocks", stocks_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/stocks/index.html.erb
<div class="col">
  <h1>Stocks</h1>

  <div id="stocks">
    <% @stocks.each do |stock| %>
      <%= render stock %>
      <p>
        <%= link_to "Show #{stock.name}", stock_path(stock.code), class: "btn btn-info" %>
        <%= link_to "Use #{stock.name} to create transaction", stock_transaction_histories_path(stock.code), class: "btn btn-success" %>
      </p>
    <% end %>
  </div>
  <%= link_to "New stock", new_stock_path, class: "btn btn-primary" %>
  <%= render "transaction_histories/go_to_clients_button" %>
</div>

app/views/stocks/new.html.erb
<h1>New stock</h1>

<%= render "form", stock: @stock %>

<br>

<div>
  <%= link_to "Back to stocks", stocks_path, class: "btn btn-secondary" %>
</div>

app/views/stocks/show.html.erb
<div class="col">
  <%= render @stock %>

  <div>
    <%= link_to "Edit this stock", edit_stock_path(@stock.code), class: "btn btn-primary" %>
    <%= link_to "Back to stocks", stocks_path, class: "btn btn-secondary" %>
    <p>
    <%= button_to "Destroy this stock", @stock, method: :delete, class: "btn btn-danger" %>
  </div>
</div>