config/routes.rb
Rails.application.routes.draw do
  concern :transaction_historyable do
    resources :transaction_histories, param: :number, only: [:index] do
      collection do
        get 'debit', controller: 'transaction_histories', action: 'debit'
        get 'credit', controller: 'transaction_histories', action: 'credit'
        post 'new_debit', controller: 'transaction_histories', action: 'new_debit'
        post 'new_credit', controller: 'transaction_histories', action: 'new_credit'
      end
    end
  end

  resources :users, :teams, :stocks, param: :code do
    concerns :transaction_historyable
  end
  
  get '*path' => redirect('/')
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/clients/user.rb
class User < Client
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user.code), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user.code), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      if params[:user].present?
        code_params = user_params[:code]
      elsif params[:code].to_i > 0
        code_params = params[:code]
      end
      #code_params = (params[:code].to_i > 0) ? params[:code] : user_params[:code]
      @user       = User.find_by_code("#{code_params}")
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user).permit(:name, :email, :code)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, include_id: false) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <form>
    <div class="col  mb-2">
      <div class="card" style="width: 36rem;">
        <div class="card-body">
            <%= form.label :name %>
            <%= form.text_field :name %>
            <%= form.label :email %>
            <%= form.text_field :email %>
            <%= form.hidden_field :code %>
          <button type="submit" class="btn btn-primary mb-2">Simpan</button>
        </div>
      </div>
    </div>

  </form>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<div class="col">
  <h1>Editing user</h1>

  <%= render "form", user: @user %>

  <br>

  <div>
    <%= link_to "Show this user", user_path(@user.code), class: "btn btn-info" %>
    <%= link_to "Back to users", users_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/users/index.html.erb
<div class="col">
  <h1>Users</h1>

  <div id="users">
    <% @users.each do |user| %>
      <%= render user %>
      <p>
        <%= link_to "Show #{user.name}", user_path(user.code), class: "btn btn-info" %>
        <%= link_to "Use #{user.name} to create transaction", user_transaction_histories_path(user.code), class: "btn btn-success" %>
      </p>
    <% end %>
  </div>
  <%= link_to "New user", new_user_path, class: "btn btn-primary" %>
  <%= render "transaction_histories/go_to_clients_button" %>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path, class: "btn btn-secondary" %>
</div>

app/views/users/show.html.erb
<div class="col">
  <%= render @user %>

  <div>
    <%= link_to "Edit this user", edit_user_path(@user.code), class: "btn btn-primary" %>
    <%= link_to "Back to users", users_path, class: "btn btn-secondary" %>
    <p>
    <%= button_to "Destroy this user", @user, method: :delete, class: "btn btn-danger" %>
  </div>
</div>