config/routes.rb
Rails.application.routes.draw do
  concern :transaction_historyable do
    resources :transaction_histories, param: :number, only: [:index] do
      collection do
        get 'debit', controller: 'transaction_histories', action: 'debit'
        get 'credit', controller: 'transaction_histories', action: 'credit'
        post 'new_debit', controller: 'transaction_histories', action: 'new_debit'
        post 'new_credit', controller: 'transaction_histories', action: 'new_credit'
      end
    end
  end

  resources :users, :teams, :stocks, param: :code do
    concerns :transaction_historyable
  end
  
  get '*path' => redirect('/')
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/transaction_history.rb
class TransactionHistory < ApplicationRecord
  include SharedMethod

  self.primary_key = :number
  
  belongs_to :user, foreign_key: 'owner_id', primary_key: 'code', class_name: 'User', optional: true
  belongs_to :team, foreign_key: 'owner_id', primary_key: 'code', class_name: 'Team', optional: true
  belongs_to :stock, foreign_key: 'owner_id', primary_key: 'code', class_name: 'Stock', optional: true
  belongs_to :wallet, foreign_key: 'sender_id', primary_key: 'address', class_name: 'Wallet'

  before_create do
    self.number = generate_uniq_key({selected: 3})
  end
end

app/controllers/transaction_histories_controller.rb
class TransactionHistoriesController < ApplicationController
  before_action :set_current_user, only: %i[ index new_debit new_credit debit credit ]

  # GET /transaction_histories or /transaction_histories.json
  def index
    current_user, @debits, @credits = Params::IndexParams.call(transaction_history_params)
    client                          = helpers.find_client_type_by_wallet(@current_user.wallet)
    @wallet_balance                 = client.find_by_code(@current_user.code).balance
    @transaction_histories          = User.includes(:transaction_histories).find_by_code(@current_user.code)
  end

  def new_debit
    #if transaction_history_params[:debit].present?
      @debit = Debit.new(transaction_history_params.except(:user_code, :team_code, :stock_code))

      if @debit.valid?
        check_balance
        if @debit.errors.any?
          redirect_back_or_to root_path, notice: @debit.errors.full_messages
        else
          @debit.save
          redirect_to "/#{helpers.find_client_type_by_wallet(@current_user.wallet).to_s.downcase}s/#{@current_user.code}/transaction_histories", notice: "Debit transaction success"
        end
      else
        redirect_back_or_to root_path, notice: @debit.errors.full_messages
      end
    #end
  end

  def new_credit
    #if transaction_history_params[:credit].present?
      @credit = Credit.new(transaction_history_params)
      
      
      if @credit.valid?
        check_balance
        if @credit.errors.any?
          redirect_back_or_to root_path, notice: @credit.errors.full_messages
        elsif @credit.valid?
          @credit.save
          redirect_to "/#{helpers.find_client_type_by_wallet(@current_user.wallet).to_s.downcase}s/#{@current_user.code}/transaction_histories", notice: "Credit transaction success"
        end
      else
        redirect_back_or_to root_path, notice: @credit.errors.full_messages
      end
    #end
  end

  def debit
    @debit  = Debit.new
  end

  def credit
    #binding.break
    @credit = Credit.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
=begin
    def set_transaction_history
      @transaction_history = TransactionHistory.find_by_number(params[:number])
    end
=end
    def set_current_user
      #binding.break
      @current_user, @user_type = Params::SetCurrentUser.call(params) 
      @transaction_histories    = TransactionHistory.where(owner_id: @current_user.code)
      
      set_available_transfer
    end

    def set_available_transfer
      @transfer_list ||= Transfers::AvailableTransfer.call(@current_user)
    end

    def check_amount
      if @credit.present? && transaction_history_params[:amount].to_d <= 0 && 
        @credit.errors.add(:base, Wallets::WalletError.call({error_type: "amount"}))
      elsif @debit.present? && transaction_history_params[:amount].to_d <= 0 && transaction_history_params[:amount].t
        @debit.errors.add(:base, Wallets::WalletError.call({error_type: "amount"}))
      else
        return true
      end
    end

    def check_balance
      setup_wallets

      if @credit.present?
        if transaction_history_params[:receiver_id] == "withdrawal" && @sender_wallet.balance < transaction_history_params[:amount].to_d
          @credit.errors.add(:base, Wallets::WalletError.call({error_type: "fund"}))
        elsif @sender_wallet.balance < transaction_history_params[:amount].to_d
          @credit.errors.add(:base, Wallets::WalletError.call({error_type: "fund"}))
        end
      end
    end
  
    def setup_wallets
      if transaction_history_params[:receiver_id] == "withdrawal" || transaction_history_params[:receiver_id] == "topup"
        sender_wallet   = Wallets::WalletFinder.call(transaction_history_params[:sender_id])
        receiver_wallet = sender_wallet
      else
        receiver_wallet = Wallets::WalletFinder.call(transaction_history_params[:receiver_id])
        sender_wallet   = Wallets::WalletFinder.call(transaction_history_params[:sender_id])
      end

      if sender_wallet.present? && receiver_wallet.present?
        @sender_wallet    = sender_wallet
        @receiver_wallet  = receiver_wallet
      elsif sender_wallet.blank?
        Wallets::WalletError.call({client_error: "sender"})
      elsif receiver_wallet.blank?
        Wallets::WalletError.call({client_error: "receiver"})
      end
    end

    # Only allow a list of trusted parameters through.
    def transaction_history_params
      params.fetch(:user_code, {})
      params.fetch(:team_code, {})
      params.fetch(:stock_code, {})
      if params[:debit].present?
        params.require(:debit).permit(:owner_id, :sender_id, :receiver_id, :amount, :description)
      elsif params[:credit].present?
        params.require(:credit).permit(:owner_id, :sender_id, :receiver_id, :amount, :description)
      else
        params.permit(:user_code, :team_code, :stock_code)
      end
    end
end

app/helpers/transaction_histories_helper.rb
module TransactionHistoriesHelper
  def find_client_code_by_wallet_address(address)
    if address.present?
      wallet      = find_client_wallet(address)
      client_type = find_client_type_by_wallet(wallet)

      if client_type == User
        return wallet.user.code
      elsif client_type == Team
        return wallet.team.code
      elsif client_type == Stock
        return wallet.stock.code
      end
    end
  end

  def find_client_name_by_transaction_history(transaction_history)
    if transaction_history.receiver_id == "withdrawal" || transaction_history.receiver_id == "topup"
      wallet      = find_client_wallet(transaction_history.sender_id)
      client_code = find_client_code_by_wallet_address(transaction_history.sender_id)
    elsif transaction_history.receiver_id.present?
      wallet      = find_client_wallet(transaction_history.receiver_id)
      client_code = find_client_code_by_wallet_address(transaction_history.receiver_id)
    else
      return nil
    end

    client  = find_client_type_by_wallet(wallet)
    user    = client.find_by_code(client_code)
    return user.name
  end

  def find_client_type_by_wallet(wallet)
    if wallet.present?
      if wallet.user.present?
        return User
      elsif wallet.team.present?
        return Team
      elsif wallet.stock.present?
        return Stock
      end
    end
  end

  def find_client_wallet(address)
    wallet = Wallet.find_by_address(address)

    return wallet
  end

  def find_client_path(address)
    if address.present?
      wallet      = find_client_wallet(address)
      client_type = find_client_type_by_wallet(wallet)

      if client_type == User
        return "users/#{wallet.user.code}"
      elsif client_type == Team
        return "teams/#{wallet.team.code}"
      elsif client_type == Stock
        return "stocks/#{wallet.stock.code}"
      end
    end
  end

  def format_amount(transaction_history)
    if check_transaction_history_type(transaction_history)
      return number_to_currency(transaction_history.amount * -1, unit: "$")
    else
      return number_to_currency(transaction_history.amount, unit: "$")
    end
  end

  def check_transaction_history_type(transaction_history)
    return true if transaction_history.type == "Credit"
  end
end

app/views/transaction_histories/_form.html.erb
<%= form_with(model: transaction_history) do |form| %>
  <% if transaction_history.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction_history.errors.count, "error") %> prohibited this transaction_history from being saved:</h2>

      <ul>
        <% transaction_history.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/transaction_histories/_go_to_clients_button.html.erb
<%= link_to "Go to users", users_path, class: "btn btn-secondary" %>
<%= link_to "Go to teams", teams_path, class: "btn btn-secondary" %>
<%= link_to "Go to stocks", stocks_path, class: "btn btn-secondary" %>

app/views/transaction_histories/_transaction_history.html.erb
<div id="<%= dom_id transaction_history %>">
</div>

app/views/transaction_histories/credit.html.erb
<!-- Credit form -->
<section>
<%= form_with(url: "/#{find_client_type_by_wallet(@current_user.wallet).to_s.downcase}s/#{@current_user.code}/transaction_histories/new_credit", scope: 'credit', model: [Credit.new, TransactionHistory.new]) do |form| %>
  <% if @credit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@credit.errors.count, "error") %> prohibited this @credit from being saved:</h2>

      <ul>
        <% @credit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-8 mb-4">
      <div class="card mb-4">
        <div class="card-header py-3">
          <h5 class="mb-0">Credit details</h5>
        </div>
        <div class="card-body">
          <form>
            <!-- 2 column grid layout with text inputs for the first and last names -->
            <div class="row mb-4">
              <div class="col">
                <div class="form-outline">
                  <%= form.hidden_field :owner_id, value: @current_user.code %>
                  <%= form.hidden_field :sender_id, value: @current_user.wallet.address %>
                  <%= form.label :receiver_id, :class => 'form-label' %>
                  <%= form.select :receiver_id, @transfer_list << 'withdrawal', {include_blank: false}, :class => 'form-control' %>
                </div>
              </div>
              <div class="col">
                <div class="form-outline">
                  <%= form.label :amount, :class => 'form-label' %>
                  <%= form.text_field :amount, :class => 'form-control' %>
                </div>
              </div>
            </div>

            <!-- Text input -->
            <div class="form-outline mb-4">
              <%= form.label :description, :class => 'form-label' %>
              <%= form.text_field :description, :class => 'form-control' %>
            </div>

            <button type="submit" class="btn btn-primary btn-lg btn-block">Simpan</button>
          </form>
        </div>
      </div>
    </div>
  </div>
<% end %>
<%= link_to "Back to #{@current_user.name} transaction histories", "/#{find_client_type_by_wallet(@current_user.wallet).to_s.downcase}s/#{@current_user.code}/transaction_histories", class: "btn btn-secondary" %>
</section>
<!-- Credit form -->

app/views/transaction_histories/debit.html.erb
<!-- Debit form -->
<section>
<%= form_with(url: "/#{find_client_type_by_wallet(@current_user.wallet).to_s.downcase}s/#{@current_user.code}/transaction_histories/new_debit", scope: 'debit', model: [Debit.new, TransactionHistory.new]) do |form| %>
  <% if @debit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@debit.errors.count, "error") %> prohibited this @debit from being saved:</h2>

      <ul>
        <% @debit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-8 mb-4">
      <div class="card mb-4">
        <div class="card-header py-3">
          <h5 class="mb-0">Debit details</h5>
        </div>
        <div class="card-body">
          <form>
            <!-- 2 column grid layout with text inputs for the first and last names -->
            <div class="row mb-4">
              <div class="col">
                <div class="form-outline">
                  <%= form.hidden_field :owner_id, value: @current_user.code %>
                  <%= form.hidden_field :sender_id, value: @current_user.wallet.address %>
                  <%= form.label :receiver_id, :class => 'form-label' %>
                  <%= form.select :receiver_id, [['Topup', 'topup']], {include_blank: false}, :class => 'form-control' %>
                </div>
              </div>
              <div class="col">
                <div class="form-outline">
                  <%= form.label :amount, :class => 'form-label' %>
                  <%= form.text_field :amount, :class => 'form-control' %>
                </div>
              </div>
            </div>

            <!-- Text input -->
            <div class="form-outline mb-4">
              <%= form.label :description, :class => 'form-label' %>
              <%= form.text_field :description, :class => 'form-control' %>
            </div>

            <button type="submit" class="btn btn-primary btn-lg btn-block">Simpan</button>
          </form>
        </div>
      </div>
    </div>
  </div>
<% end %>
<%= link_to "Back to #{@current_user.name} transaction histories", "/#{find_client_type_by_wallet(@current_user.wallet).to_s.downcase}s/#{@current_user.code}/transaction_histories", class: "btn btn-secondary" %>
</section>
<!-- Debit form -->

app/views/transaction_histories/edit.html.erb
<h1>Editing transaction history</h1>

<%= render "form", transaction_history: @transaction_history %>

<br>

<div>
  <%= link_to "Show this transaction history", @transaction_history %> |
  <%= link_to "Back to transaction histories", transaction_histories_path %>
</div>

app/views/transaction_histories/index.html.erb
<div class="col">
  <h1><%= @current_user.name %> Transaction Histories</h1>
  <h5>Wallet balance: <%= @wallet_balance %> </h5>

  <div id="transaction_histories">
    <% if @transaction_histories.present? %>
      <%= link_to("Debit", "/#{find_client_type_by_wallet(@current_user.wallet).to_s.downcase}s/#{@current_user.code}/transaction_histories/debit", class: "btn btn-primary") %>
      <%= link_to("Credit", "/#{find_client_type_by_wallet(@current_user.wallet).to_s.downcase}s/#{@current_user.code}/transaction_histories/credit", class: "btn btn-primary") %>

    <div class="row">
      <div class="col-md-4 col-md-6 col-md-6 col-md-6">
        <h3>Debit</h3>
        <table class="table">
          <thead>
            <tr>
              <th>Sender</th>
              <th>Receiver</th>
              <th>Amount</th>
              <th>Description</th>
            </tr>
          </thead>
          <% @debits.order(created_at: :desc).each do |transaction_history| %>
            <div id="<%= dom_id transaction_history %>">
              <tbody>
                <tr>
                  <td><%= transaction_history.sender_id.truncate(10) %></td>
                  <td><%= link_to("View #{find_client_name_by_transaction_history(transaction_history) || @current_user.name} transaction histories", "/#{find_client_path(transaction_history.receiver_id) || "#{find_client_type_by_wallet(@current_user.wallet).to_s.downcase}s/#{@current_user.code}"}/transaction_histories", target: "_blank") %></td>
                  <td><%= format_amount(transaction_history) %></td>
                  <td><%= transaction_history.description %></td>
                </tr>
              </tbody>
            </div>
          <% end %>
        </table>
      </div>
      <div class="col-md-4 col-md-6 col-md-6 col-md-6">
        <h3>Credit</h3>
        <table class="table">
          <thead>
            <tr>
              <th>Sender</th>
              <th>Receiver</th>
              <th>Amount</th>
              <th>Description</th>
            </tr>
          </thead>
          <% @credits.order(created_at: :desc).each do |transaction_history| %>
            <div id="<%= dom_id transaction_history %>">
              <tbody>
                <tr>
                  <td><%= transaction_history.sender_id.truncate(10) %></td>
                  <td><%= link_to("View #{find_client_name_by_transaction_history(transaction_history) || @current_user.name} transaction histories", "/#{find_client_path(transaction_history.receiver_id)}/transaction_histories", target: "_blank") %></td>
                  <td><%= format_amount(transaction_history) %></td>
                  <td><%= transaction_history.description %></td>
                </tr>
              </tbody>
            </div>
          <% end %>
        </table>
      </div>
    </div>
    <% else %>
      <%= link_to("Debit", "/#{find_client_type_by_wallet(@current_user.wallet).to_s.downcase}s/#{@current_user.code}/transaction_histories/debit", class: "btn btn-primary") %>
      <%= link_to("Credit", "/#{find_client_type_by_wallet(@current_user.wallet).to_s.downcase}s/#{@current_user.code}/transaction_histories/credit", class: "btn btn-primary") %>
      <p>
    <% end %>
  </div>
  <%= render "go_to_clients_button" %>
</div>